name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly 2
      # and run all Cypress tests 2
      - name: Cypress run
        uses: cypress-io/github-action@v2