name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      ref:
        description: 'The ref (branch, tag, or commit SHA) to check out, build, and deploy'
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: CloneTest
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
