name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      ref:
        description: 'The ref (branch, tag, or commit SHA) to check out, build, and deploy'
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: CloneTest
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
    - name: CreateTag
      uses: actions/github-script@v3
      with:
        github-token: ${{ github.token }}
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "4e6cbc7366b97369a2fd1c3701876266c8c27f39",
            sha: context.sha
          })
          
